import type { Row } from "$lib/types/types";

export const dataAtRhinos: Row[] = [
    {
        pn: '001',
        fp: '025',
        hs: 'm',
        do: '1',
        di: '10',
        frm: 'spread',
        str: 'l',
        qbs: 'p',
        qn: '01',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '22',
        xn: '89',
        yn: '83',
        hn: '27',
        zn: '88',
        mp: 'y',
        mt: 'jet',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'post',
        ya: 'q out',
        ha: 'out',
        za: 'fade',
        tt: 'y',
        rn: '83',
        ctch: 'good',
        cmt: '-'
    },
    {
        pn: '002',
        fp: '029',
        hs: 'm',
        do: '2',
        di: '06',
        frm: 'spread',
        str: 'l',
        qbs: 'p',
        qn: '01',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '22',
        xn: '89',
        yn: '83',
        hn: '27',
        zn: '88',
        mp: '-',
        mt: '-',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'in',
        ya: 'fade',
        ha: 'slant',
        za: 'slant',
        tt: 'x',
        rn: '89',
        ctch: 'bad',
        cmt: '-'
    },
    {
        pn: '003',
        fp: '029',
        hs: 'm',
        do: '3',
        di: '06',
        frm: 'spread',
        str: 'r',
        qbs: 'p',
        qn: '01',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '22',
        xn: '88',
        yn: '27',
        hn: '83',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'r',
        bs: 'zone left',
        qa: '-',
        ta: 'i zone b',
        xa: '-',
        ya: '-',
        ha: '-',
        za: '-',
        tt: '-',
        rn: '-',
        ctch: '-',
        cmt: '-'
    },
    {
        pn: '004',
        fp: '046',
        hs: 'r',
        do: '1',
        di: '10',
        frm: 'spread',
        str: 'r',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '27',
        hn: '83',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'r',
        bs: 'zone left',
        qa: '-',
        ta: 'i zone b',
        xa: '-',
        ya: '-',
        ha: '-',
        za: '-',
        tt: '-',
        rn: '-',
        ctch: '-',
        cmt: '-'
    },
    {
        pn: '005',
        fp: '052',
        hs: 'm',
        do: '2',
        di: '04',
        frm: 'spread',
        str: 'r',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '83',
        hn: '39',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'r',
        bs: 'dive str',
        qa: '-',
        ta: 'dive a',
        xa: '-',
        ya: '-',
        ha: '-',
        za: '-',
        tt: '-',
        rn: '-',
        ctch: '-',
        cmt: '-'
    },
    {
        pn: '006',
        fp: '051',
        hs: 'm',
        do: '3',
        di: '05',
        frm: 'spread',
        str: 'r',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '83',
        hn: '39',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'fade',
        ya: 'out',
        ha: 'corner',
        za: 'hitch',
        tt: 'x',
        rn: '89',
        ctch: 'bad',
        cmt: '-'
    }
];
