import type { Row } from "$lib/types/types";

export const dataAtRhinos: Row[] = [
    {
        pn: '1',
        fp: 'o25',
        hs: 'middle',
        do: '1',
        di: '10',
        frm: 'spread',
        str: 'left',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '22',
        xn: '89',
        yn: '83',
        hn: '27',
        zn: '88',
        mp: 'y',
        mt: 'jet',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'post',
        ya: 'q out',
        ha: 'out',
        za: 'fade',
        tt: 'y',
        rn: '83',
        ctch: 'good',
        cmt: '-'
    },
    {
        pn: '2',
        fp: 'o29',
        hs: 'left',
        do: '2',
        di: '6',
        frm: 'spread',
        str: 'left',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '22',
        xn: '89',
        yn: '83',
        hn: '27',
        zn: '88',
        mp: '-',
        mt: '-',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'in',
        ya: 'fade',
        ha: 'slant',
        za: 'slant',
        tt: 'x',
        rn: '89',
        ctch: 'bad',
        cmt: '-'
    },
    {
        pn: '3',
        fp: 'o29',
        hs: 'left',
        do: '3',
        di: '6',
        frm: 'spread',
        str: 'right',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '22',
        xn: '88',
        yn: '27',
        hn: '83',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'r',
        bs: 'zone left',
        qa: '-',
        ta: 'i zone b',
        xa: '-',
        ya: '-',
        ha: '-',
        za: '-',
        tt: '-',
        rn: '-',
        ctch: '-',
        cmt: '-'
    },
    {
        pn: '4',
        fp: 'o46',
        hs: 'right',
        do: '1',
        di: '10',
        frm: 'spread',
        str: 'right',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '27',
        hn: '83',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'r',
        bs: 'zone left',
        qa: '-',
        ta: 'i zone b',
        xa: '-',
        ya: '-',
        ha: '-',
        za: '-',
        tt: '-',
        rn: '-',
        ctch: '-',
        cmt: '-'
    },
    {
        pn: '5',
        fp: 'e48',
        hs: 'middle',
        do: '2',
        di: '4',
        frm: 'spread',
        str: 'right',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '83',
        hn: '39',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'r',
        bs: 'dive str',
        qa: '-',
        ta: 'dive a',
        xa: '-',
        ya: '-',
        ha: '-',
        za: '-',
        tt: '-',
        rn: '-',
        ctch: '-',
        cmt: '-'
    },
    {
        pn: '6',
        fp: 'e49',
        hs: 'middle',
        do: '3',
        di: '5',
        frm: 'spread',
        str: 'right',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '83',
        hn: '39',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'fade',
        ya: 'out',
        ha: 'corner',
        za: 'hitch',
        tt: 'x',
        rn: '89',
        ctch: 'bad',
        cmt: '-'
    },
    {
        pn: '12',
        fp: 'o30',
        hs: 'middle',
        do: '1',
        di: '10',
        frm: 'trips',
        str: 'right',
        qbs: 'p',
        qn: '12',
        lt: '67',
        lg: '69',
        ct: '66',
        rg: '74',
        rt: '78',
        tn: '21',
        xn: '88',
        yn: '83',
        hn: '39',
        zn: '89',
        mp: '-',
        mt: '-',
        pt: 'p',
        bs: 'pass',
        qa: '-',
        ta: 'pass',
        xa: 'q in',
        ya: 'q in',
        ha: 'in',
        za: 'dug',
        tt: 'z',
        rn: '89',
        ctch: 'int',
        cmt: '-'
    }
];
